FROM rocker/r-ver:4.4.2 AS production
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -y
RUN apt-get install -y apt-utils software-properties-common gpg curl apt-utils
RUN curl -sS https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor | tee /etc/apt/trusted.gpg.d/cloud-sdk-bullseye.gpg
RUN apt-get update && apt-get install -y \
    libssl-dev \
    libcurl4-openssl-dev \
    libxml2-dev \
    libfontconfig1-dev \
    libharfbuzz-dev \
    libfribidi-dev \
    libfreetype6-dev \
    libpng-dev \
    libtiff5-dev \
    libjpeg-dev \
    libgdal-dev \
    libgeos-dev \
    libproj-dev \
    libudunits2-dev \
    gcc g++\
    git \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN install2.r --repos 'http://cran.rstudio.com/' renv
WORKDIR /opt/gfw/src

RUN ssh-keyscan github.com >>  /etc/ssh/ssh_known_hosts
RUN --mount=type=ssh ssh -T git@github.com
COPY . .
RUN --mount=type=ssh Rscript -e "renv::restore()"
