FROM rocker/tidyverse:4.4.2 AS devbase
ENV DEBIAN_FRONTEND=noninteractive


RUN apt-get update -y
RUN apt-get install -y apt-utils software-properties-common gpg curl apt-utils
RUN curl -sS https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor | tee /etc/apt/trusted.gpg.d/cloud-sdk-bullseye.gpg
RUN apt-get update && apt-get install -y \
    libssl-dev libcurl4-openssl-dev \
    openssh-client \
    libxml2-dev \
    libfontconfig1-dev \
    libharfbuzz-dev \
    libfribidi-dev libfreetype6-dev \
    libpng-dev libtiff5-dev libjpeg-dev \
    libgdal-dev libgeos-dev libproj-dev \
    libudunits2-dev \
    iputils-ping \
    gcc g++ \
    git

FROM devbase AS devdeps

RUN apt-get install -y sudo
RUN apt-get install -y sl tree
RUN apt-get update && \
    apt-get install -y python3 python3-pip

RUN echo 'export PATH="$HOME/.local/bin:/usr/games:/usr/local/games:$PATH"' >> /etc/profile
RUN echo file-monitor-include-hidden=true >> /etc/rstudio/rserver.conf

FROM devdeps AS userdeps

RUN ssh-keyscan github.com >> /etc/ssh/ssh_known_hosts
RUN --mount=type=ssh ssh -T git@github.com 2>&1 | grep "successfully authenticated"

USER rstudio

ENV RENV_PATHS_LIBRARY=/home/rstudio/library
RUN mkdir -p /home/rstudio/src/
RUN mkdir -p ${RENV_PATHS_LIBRARY}

WORKDIR /home/rstudio/src

RUN install2.r --repos 'http://cran.rstudio.com/' renv

RUN python3 -m pip install --upgrade --break-system-packages pip
RUN python3 -m pip install --break-system-packages pre-commit


# USER root
# # RUN ping -c 3 github.com
# COPY ./renv.lock .
# COPY ./renv .
# RUN --mount=type=ssh Rscript -e "renv::restore()"

# RUN ping -c 3 github.com
# RUN --mount=type=ssh ssh -T git@github.com
# RUN --mount=type=ssh Rscript -e "renv::install('git+ssh://git@github.com/GlobalFishingWatch/fishwatchr.git')"

FROM userdeps AS development
USER root
