safe_table_get:
  project: world-fishing-827
  dataset: prj_forced_labor
  scratch: true
  scratch_location: scratch_philip
  query_directory: ../queries
  tables:
    - name: iuu_ucsb
      dataset: prj_forced_labor
      scratch: false
    - name: all_iuu
      dataset: prj_forced_labor
      scratch: false
    - name: vi_ssvid_v20220101
      dataset: gfw_research
      scratch: false
    - name: eez_info
      dataset: gfw_research
      scratch: false
    - name: flags_of_convenience_v20211013
      dataset: gfw_research
      scratch: false
    - name: fishing_vessels_ssvid_v20220801
      dataset: gfw_research
      scratch: false
    - name: vi_ssvid_byyear_v20220801
      dataset: gfw_research
      scratch: false
    - name: all_vessels_v20220801
      dataset: vessel_database
      scratch: false
    - name: loitering
      dataset: pipe_production_v20201001
      scratch: false
    - name: research_segs
      dataset: pipe_production_v20201001
      scratch: false
    - name: proto_published_events_ais_gaps
      dataset: pipe_production_v20201001
      scratch: false
    - name: research_messages
      dataset: pipe_production_v20201001
      scratch: false
